### ISSUE TITLE
Module should display local shelving instead of main shelving

### ISSUE THREAD

**Issue by bechster** [vejlebib/vejlebib_fbs#1] opened 2017-08-24 08:28 UTC
In DDB CMS vejlebib_fbs displays Field 652, subfield M. This is the main shelving (da_DK: hovedopstilling) - which at some point has been altered in the data well by DBC.

However, it should display the local shelving defined in Field 652 - in the trail record (da_DK: påhængspost).

Would it be possible to make a query that checks if a trail record is available, and if it is, display the classification number fromt the trail record?

**DDB CMS is displaying the classification number from the main shelving:**
![screendump-ddbcms](https://user-images.githubusercontent.com/740084/29656316-673c340c-88b4-11e7-917d-0cb665ef8a3b.jpg)

**See also main and trail records in Cicero:**
![cicero-main-record](https://user-images.githubusercontent.com/740084/29656317-673c680a-88b4-11e7-865d-06005b4b5dcb.jpg)

![cicero-trail-record](https://user-images.githubusercontent.com/740084/29656318-67413fce-88b4-11e7-9654-a74b733503ba.jpg)

**Comment by holt83** [comment] 2017-09-22 11:14
The functionality provided by this module has been merged in core in may this year, so it will probably be in next release:

https://github.com/ding2/ting-client/pull/21
https://github.com/ding2/ding2/pull/552

It also adresses the issue decscribed here, where it uses the wrong marc post. More specifically this commit: 
https://github.com/ding2/ting-client/pull/21/commits/acdec1062a36f1cf840d68e4bf2b3ce2693df315

So you need to make sure to remove the old vejlebib_fbs module, when moving to the next version. A way to check if your current DDB CMS version includes this functionality, is by navigating to /admin/config/ting/holdings and verifying that your able to choose 'Alma shelfmark' under 'Holdings suffix'.

Closing this issue since the issue is fixed in core.

**Closed as completed** 2017-09-22 11:19 UTC
